# Generated by Django 4.1.5 on 2023-02-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='data_update',
        ),
        migrations.AddField(
            model_name='inventory',
            name='cost_per_piece',
            field=models.IntegerField(default=True),
        ),
    ]
